<a href="https://colab.research.google.com/github/lungnahahd/Tensorflow_Prac/blob/main/Tensorflow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import tensorflow as tf

In [3]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
데이터 = pd.read_csv(파일경로)
데이터 = pd.get_dummies(데이터)

In [5]:
print(데이터.head)

<bound method NDFrame.head of      꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]>


In [6]:
원인 = 데이터[['꽃잎길이','꽃잎폭','꽃받침길이', '꽃받침폭']]
결과 = 데이터[['품종_setosa','품종_versicolor','품종_virginica' ]]
print(원인.shape, 결과.shape)

(150, 4) (150, 3)


In [8]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3,activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy')

In [15]:
model.fit(원인, 결과, epochs=1000, verbose=0)

In [16]:
model.fit(원인,결과,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1338
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1334
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1334
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1335
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1332
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1331
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1334
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1338
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1329
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1327


In [17]:
print(model.predict(원인[:5]))
print(결과[:5])

[[9.9961406e-01 3.8591863e-04 2.3580304e-09]
 [9.9853384e-01 1.4660932e-03 3.4749096e-08]
 [9.9923217e-01 7.6781539e-04 1.0718966e-08]
 [9.9739754e-01 2.6023656e-03 6.3528951e-08]
 [9.9965167e-01 3.4831293e-04 1.7419147e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [18]:
print(model.predict(원인[-5:]))
print(결과[-5:])

[[7.63139241e-08 6.04272671e-02 9.39572632e-01]
 [1.85930730e-07 1.04310036e-01 8.95689785e-01]
 [3.94437819e-07 1.82381079e-01 8.17618608e-01]
 [6.65711681e-08 9.52909067e-02 9.04709041e-01]
 [8.75820433e-07 3.14646482e-01 6.85352623e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
